//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Challenge.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Challenge.Domain.Resources.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling reservation.
        /// </summary>
        public static string CancellingReservation {
            get {
                return ResourceManager.GetString("CancellingReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating outbox.
        /// </summary>
        public static string CreatingOutbox {
            get {
                return ResourceManager.GetString("CreatingOutbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating reservation.
        /// </summary>
        public static string CreatingReservation {
            get {
                return ResourceManager.GetString("CreatingReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting &apos;{0}&apos;.
        /// </summary>
        public static string DeletingObject {
            get {
                return ResourceManager.GetString("DeletingObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifying reservation: {0}.
        /// </summary>
        public static string NotifyingReservation {
            get {
                return ResourceManager.GetString("NotifyingReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Deleted: &apos;{1}&apos;.
        /// </summary>
        public static string ObjectDeleted {
            get {
                return ResourceManager.GetString("ObjectDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Saved: &apos;{1}&apos;.
        /// </summary>
        public static string ObjectSaved {
            get {
                return ResourceManager.GetString("ObjectSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple &apos;{0}&apos; proccessed.
        /// </summary>
        public static string ObjectsProcessed {
            get {
                return ResourceManager.GetString("ObjectsProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Updated: &apos;{1}&apos;.
        /// </summary>
        public static string ObjectUpdated {
            get {
                return ResourceManager.GetString("ObjectUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutboxCreated: {0}.
        /// </summary>
        public static string OutboxCreated {
            get {
                return ResourceManager.GetString("OutboxCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing multiple &apos;{0}&apos;.
        /// </summary>
        public static string ProcessingObjects {
            get {
                return ResourceManager.GetString("ProcessingObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation cancelled: {0}.
        /// </summary>
        public static string ReservationCancelled {
            get {
                return ResourceManager.GetString("ReservationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifying reservation: {0}.
        /// </summary>
        public static string ReservationCreated {
            get {
                return ResourceManager.GetString("ReservationCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifying reservation: {0}.
        /// </summary>
        public static string ReservationNotified {
            get {
                return ResourceManager.GetString("ReservationNotified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifying reservation: {0}.
        /// </summary>
        public static string ReservationSaved {
            get {
                return ResourceManager.GetString("ReservationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation updated: {0}.
        /// </summary>
        public static string ReservationUpdated {
            get {
                return ResourceManager.GetString("ReservationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving &apos;{0}&apos;.
        /// </summary>
        public static string SavingObject {
            get {
                return ResourceManager.GetString("SavingObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving reservation.
        /// </summary>
        public static string SavingReservation {
            get {
                return ResourceManager.GetString("SavingReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updateing &apos;{0}&apos;.
        /// </summary>
        public static string UpdatingObject {
            get {
                return ResourceManager.GetString("UpdatingObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating reservation.
        /// </summary>
        public static string UpdatingReservation {
            get {
                return ResourceManager.GetString("UpdatingReservation", resourceCulture);
            }
        }
    }
}
