//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Challenge.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TemplateParameters {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TemplateParameters() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Challenge.Domain.Resources.TemplateParameters", typeof(TemplateParameters).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola [UserName],
        ///
        ///Lamentamos informarte que tu reserva de vuelo ha sido cancelada. Entendemos que las circunstancias pueden cambiar y respetamos tu decisión de cancelar la reserva.
        ///
        ///Detalles de la reserva cancelada:
        ///
        ///ID de la Reserva: [ReservationId]
        ///Fecha de Salida: [DepartureTime]
        ///Origen: [OriginCityName]
        ///Destino: [DestinationCityName]
        ///Hemos procesado tu solicitud de cancelación y hemos confirmado la misma.
        ///
        ///Si necesitas más asistencia o deseas hacer otra reserva en el futuro, no dudes en ponerte en conta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CancelReservationEmailBody {
            get {
                return ResourceManager.GetString("CancelReservationEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importante: Cancelación de Reserva de Vuelo.
        /// </summary>
        internal static string CancelReservationEmailSubject {
            get {
                return ResourceManager.GetString("CancelReservationEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola [UserName],
        ///
        ///¡Tu reserva de vuelo ha sido creada con éxito!
        ///
        ///Detalles de la reserva:
        ///
        ///ID de la Reserva: [ReservationId]
        ///Fecha de Salida: [DepartureTime]
        ///Origen: [OriginCityName]
        ///Destino: [DestinationCityName]
        ///Número de Asiento: [SeatNumber]
        ///Gracias por elegir nuestra aerolínea. ¡Esperamos que tengas un excelente vuelo!.
        /// </summary>
        internal static string CreateReservationEmailBody {
            get {
                return ResourceManager.GetString("CreateReservationEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmación de Reserva de Vuelo.
        /// </summary>
        internal static string CreateReservationEmailSubject {
            get {
                return ResourceManager.GetString("CreateReservationEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DepartureTime].
        /// </summary>
        internal static string DepartureTime {
            get {
                return ResourceManager.GetString("DepartureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DestinationCityName].
        /// </summary>
        internal static string DestinationCityName {
            get {
                return ResourceManager.GetString("DestinationCityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OriginCityName].
        /// </summary>
        internal static string OriginCityName {
            get {
                return ResourceManager.GetString("OriginCityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ReservationId].
        /// </summary>
        internal static string ReservationId {
            get {
                return ResourceManager.GetString("ReservationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SeatNumber].
        /// </summary>
        internal static string SeatNumber {
            get {
                return ResourceManager.GetString("SeatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola [UserName],
        ///
        ///Te informamos que tu reserva de vuelo ha sido actualizada con éxito. A continuación, encontrarás los detalles actualizados de tu vuelo:
        ///
        ///Detalles de la reserva actualizada:
        ///
        ///ID de la Reserva: [ReservationId]
        ///Nueva Fecha de Salida: [DepartureTime]
        ///Origen: [OriginCityName]
        ///Destino: [DestinationCityName]
        ///Nuevo Número de Asiento: [SeatNumber]
        ///Si tienes alguna pregunta o necesitas asistencia adicional, no dudes en ponerte en contacto con nuestro equipo de soporte. ¡Gracias por seguir [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateReservationEmailBody {
            get {
                return ResourceManager.GetString("UpdateReservationEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualización de Reserva de Vuelo.
        /// </summary>
        internal static string UpdateReservationEmailSubject {
            get {
                return ResourceManager.GetString("UpdateReservationEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [UserName].
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
