//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Challenge.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Challenge.Domain.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Invalid data for new record.
        /// </summary>
        public static string ActionRegisterDenied {
            get {
                return ResourceManager.GetString("ActionRegisterDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Invalid data to update record.
        /// </summary>
        public static string ActionUpdateDenied {
            get {
                return ResourceManager.GetString("ActionUpdateDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot register a processed event.
        /// </summary>
        public static string CannotRegisterAProcessedEvent {
            get {
                return ResourceManager.GetString("CannotRegisterAProcessedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Must have {1} to {2} characters.
        /// </summary>
        public static string CharacterRangeData {
            get {
                return ResourceManager.GetString("CharacterRangeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Must be a date between {1} and {2}.
        /// </summary>
        public static string DateRangeData {
            get {
                return ResourceManager.GetString("DateRangeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection &quot;{0}&quot; not found.
        /// </summary>
        public static string DbConnectionNotFound {
            get {
                return ResourceManager.GetString("DbConnectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Invalid email format: &apos;{1}&apos;.
        /// </summary>
        public static string EmailFormat {
            get {
                return ResourceManager.GetString("EmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Cannot be empty.
        /// </summary>
        public static string EmptyData {
            get {
                return ResourceManager.GetString("EmptyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Cannot be empty or null.
        /// </summary>
        public static string EmptyOrNullData {
            get {
                return ResourceManager.GetString("EmptyOrNullData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Cannot be empty, null, or only spaces.
        /// </summary>
        public static string EmptyOrNullWithSpacesData {
            get {
                return ResourceManager.GetString("EmptyOrNullWithSpacesData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Must be a date greater than {1}.
        /// </summary>
        public static string GreaterThanDateData {
            get {
                return ResourceManager.GetString("GreaterThanDateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Must be a number greater than {1}.
        /// </summary>
        public static string GreaterThanNumberData {
            get {
                return ResourceManager.GetString("GreaterThanNumberData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Must be a date less than {1}.
        /// </summary>
        public static string LessThanDateData {
            get {
                return ResourceManager.GetString("LessThanDateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Must be a number less than {1}.
        /// </summary>
        public static string LessThanNumberData {
            get {
                return ResourceManager.GetString("LessThanNumberData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Not found: {1}.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not a defined value for the enum type &apos;{1}&apos;..
        /// </summary>
        public static string NotFoundEnumValue {
            get {
                return ResourceManager.GetString("NotFoundEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Cannot be null.
        /// </summary>
        public static string NullData {
            get {
                return ResourceManager.GetString("NullData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Must be a number between &apos;{1}&apos; and &apos;{2}&apos;.
        /// </summary>
        public static string NumberRangeData {
            get {
                return ResourceManager.GetString("NumberRangeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} has no interface.
        /// </summary>
        public static string ServiceHasNoInterface {
            get {
                return ResourceManager.GetString("ServiceHasNoInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - The value &apos;{1}&apos; is not allowed.
        /// </summary>
        public static string ValueNotAllowedData {
            get {
                return ResourceManager.GetString("ValueNotAllowedData", resourceCulture);
            }
        }
    }
}
