version: '3.4'

services:
  challenge.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"  
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - challenge.database
      - challenge.rabbitmq

  challenge.outbox.publisherworker:
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    depends_on:
      - challenge.database

  challenge.broker.notificationworker:
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    depends_on:
      - challenge.database
      - challenge.rabbitmq

  challenge.rabbitmq:
    environment:
      RABBITMQ_DEFAULT_USER: challenge-user
      RABBITMQ_DEFAULT_PASS: challenge-pw
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # Management plugin default port

  challenge.database:
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=challenge-user
      - POSTGRES_PASSWORD=challenge-pw
      - POSTGRES_DB=challenge-db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  challenge.pgadmin4:
    environment: 
      PGADMIN_DEFAULT_EMAIL: "challenge.user@pgsql.com"
      PGADMIN_DEFAULT_PASSWORD: "challenge-pw"
    ports:
      - "8080:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on: 
      - challenge.database

volumes:
    dbdata:
    pgadmin: